replicaCount: 2

image:
  repository: ghcr.io/example/qsafe-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8443

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 512Mi

env:
  PQ_MODE: strict
  SESSION_ROTATION_S: "900"

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
